import {ChoiceDbModel} from "@/dataScheme/DataModel";

export default (<ChoiceDbModel[]>[
    { id: 1 , parameterId: 1 , relatedExpressionId: 0,  title: 'Малоэтажный жилой дом'},
    { id: 2 , parameterId: 1 , relatedExpressionId: 0,  title: 'Среднеэтажный жилой дом'},
    { id: 3 , parameterId: 1 , relatedExpressionId: 0,  title: 'Многоэтажный жилой дом'},
    { id: 4 , parameterId: 1 , relatedExpressionId: 0,  title: 'Линейные объекты'},
    { id: 5 , parameterId: 1 , relatedExpressionId: 0,  title: 'Производственного или коммерческого назначения'},
    { id: 6 , parameterId: 2 , relatedExpressionId: 0,  title: 'Для проживания граждан'},
    { id: 7 , parameterId: 2 , relatedExpressionId: 0,  title: 'Для производственной деятельности'},
    { id: 8 , parameterId: 2 , relatedExpressionId: 0,  title: 'Не для проживания граждан и производственной деятельности'},
    { id: 9 , parameterId: 3 , relatedExpressionId: 0,  title: 'Не более 1500м2'},
    { id: 10, parameterId: 4 , relatedExpressionId: 0,  title: 'Не более 2 этажей'},
    { id: 11, parameterId: 4 , relatedExpressionId: 0,  title: 'До 4-х этажей'},
    { id: 12, parameterId: 4 , relatedExpressionId: 0,  title: 'Не выше 8 этажей'},
    { id: 13, parameterId: 4 , relatedExpressionId: 0,  title: '9 и выше'},
    { id: 14, parameterId: 5 , relatedExpressionId: 0,  title: 'Район'},
    { id: 15, parameterId: 5 , relatedExpressionId: 0,  title: 'Город'},
    { id: 16, parameterId: 6 , relatedExpressionId: 0,  title: 'Право собственности'},
    { id: 17, parameterId: 6 , relatedExpressionId: 0,  title: 'Право аренды'},
    { id: 18, parameterId: 7 , relatedExpressionId: 0,  title: 'Предполагается'},
    { id: 19, parameterId: 7 , relatedExpressionId: 0,  title: 'Не предполагается'},
    { id: 20, parameterId: 8 , relatedExpressionId: 0,  title: 'Да'},
    { id: 21, parameterId: 8 , relatedExpressionId: 0,  title: 'Нет'},
    { id: 22, parameterId: 9, relatedExpressionId: 0,  title: 'Объект в границе зоны'},
    { id: 23, parameterId: 9, relatedExpressionId: 0,  title: 'Объект не в границе зоны'},
    { id: 24, parameterId: 10, relatedExpressionId: 0,  title: 'Объект в границе зоны'},
    { id: 25, parameterId: 10, relatedExpressionId: 0,  title: 'Объект не в границе зоны'},
    { id: 26, parameterId: 11, relatedExpressionId: 0,  title: 'Объект в границе зоны'},
    { id: 27, parameterId: 11, relatedExpressionId: 0,  title: 'Объект не в границе зоны'},
    { id: 28, parameterId: 12, relatedExpressionId: 0,  title: 'Объект в границе зоны'},
    { id: 29, parameterId: 12, relatedExpressionId: 0,  title: 'Объект не в границе зоны'},
    { id: 30, parameterId: 13, relatedExpressionId: 0,  title: 'Да'},
    { id: 31, parameterId: 13, relatedExpressionId: 0,  title: 'Нет'},
    { id: 32, parameterId: 14, relatedExpressionId: 0,  title: 'Да'},
    { id: 33, parameterId: 14, relatedExpressionId: 0,  title: 'Нет'},
    { id: 34, parameterId: 15, relatedExpressionId: 0,  title: 'Да'},
    { id: 35, parameterId: 15, relatedExpressionId: 0,  title: 'Нет'},
    { id: 36, parameterId: 16, relatedExpressionId: 0,  title: 'Да'},
    { id: 37, parameterId: 16, relatedExpressionId: 0,  title: 'Нет'},
    { id: 38, parameterId: 17, relatedExpressionId: 0,  title: 'Да'},
    { id: 39, parameterId: 17, relatedExpressionId: 0,  title: 'Нет'},
    { id: 40, parameterId: 18, relatedExpressionId: 0,  title: 'Да'},
    { id: 41, parameterId: 18, relatedExpressionId: 0,  title: 'Нет'},
    { id: 42, parameterId: 19, relatedExpressionId: 0,  title: 'Да'},
    { id: 43, parameterId: 19, relatedExpressionId: 0,  title: 'Нет'},
    { id: 44, parameterId: 20, relatedExpressionId: 0,  title: 'Государственная экспертиза'},
    { id: 45, parameterId: 20, relatedExpressionId: 0,  title: 'Негосударственная экспертиза'},
    { id: 46, parameterId: 20, relatedExpressionId: 0,  title: 'Не предполагается'},
    { id: 47, parameterId: 21, relatedExpressionId: 0,  title: 'Предполагается'},
    { id: 48, parameterId: 21, relatedExpressionId: 0,  title: 'Не предполагается'},
    { id: 49, parameterId: 22, relatedExpressionId: 0,  title: 'Да'},
    { id: 50, parameterId: 22, relatedExpressionId: 0,  title: 'Нет'},
    { id: 51, parameterId: 23, relatedExpressionId: 0,  title: 'Предполагается'},
    { id: 52, parameterId: 23, relatedExpressionId: 0,  title: 'Не предполагается'}
]);
