import {ChoiceDbModel} from "@/dataScheme/DataModel";

export default (<ChoiceDbModel[]>[
    { id: 1 , parameterId: 1 , relatedExpressionId: 0,  title: 'Малоэтажный жилой дом'},
    { id: 2 , parameterId: 1 , relatedExpressionId: 0,  title: 'Среднеэтажный жилой дом'},
    { id: 3 , parameterId: 1 , relatedExpressionId: 0,  title: 'Многоэтажный жилой дом'},
    { id: 4 , parameterId: 1 , relatedExpressionId: 0,  title: 'Линейные объекты'},
    { id: 5 , parameterId: 1 , relatedExpressionId: 0,  title: 'Производственного и коммерческого назначения'},
    { id: 6 , parameterId: 2 , relatedExpressionId: 0,  title: 'Жилого назначения'},
    { id: 7 , parameterId: 2 , relatedExpressionId: 0,  title: 'Производственного и коммерческого назначения'},
    { id: 8 , parameterId: 3 , relatedExpressionId: 0,  title: 'г.Тамбов'},
    { id: 9 , parameterId: 4 , relatedExpressionId: 0,  title: 'не более 1500 м2'},
    { id: 10, parameterId: 5 , relatedExpressionId: 0,  title: 'не более 2 этажа'},
    { id: 11, parameterId: 5 , relatedExpressionId: 0,  title: 'до 4-х этажей'},
    { id: 12, parameterId: 5 , relatedExpressionId: 0,  title: 'не выше 8 этажей'},
    { id: 13, parameterId: 5 , relatedExpressionId: 0,  title: '9 и выше'},
    { id: 14, parameterId: 6 , relatedExpressionId: 0,  title: 'Объект в границе зоны'},
    { id: 15, parameterId: 6 , relatedExpressionId: 0,  title: 'Объект не в границе зоны'},
    { id: 16, parameterId: 7 , relatedExpressionId: 0,  title: 'Объект в границе зоны'},
    { id: 17, parameterId: 7 , relatedExpressionId: 0,  title: 'Объект не в границе зоны'},
    { id: 18, parameterId: 8 , relatedExpressionId: 0,  title: 'Требуется'},
    { id: 19, parameterId: 8 , relatedExpressionId: 0,  title: 'Не требуется'},
    { id: 20, parameterId: 9 , relatedExpressionId: 0,  title: 'Да'},
    { id: 21, parameterId: 9 , relatedExpressionId: 0,  title: 'Нет'},
    { id: 22, parameterId: 10, relatedExpressionId: 0,  title: 'Да'},
    { id: 23, parameterId: 10, relatedExpressionId: 0,  title: 'Нет'},
    { id: 24, parameterId: 11, relatedExpressionId: 0,  title: 'Да'},
    { id: 25, parameterId: 11, relatedExpressionId: 0,  title: 'Нет'},
    { id: 26, parameterId: 12, relatedExpressionId: 0,  title: 'Да'},
    { id: 27, parameterId: 12, relatedExpressionId: 0,  title: 'Нет'},
    { id: 28, parameterId: 13, relatedExpressionId: 0,  title: 'Государственная экспертиза'},
    { id: 29, parameterId: 13, relatedExpressionId: 0,  title: 'Негосударственная экспертиза'},
    { id: 30, parameterId: 13, relatedExpressionId: 0,  title: 'Не проводится'},
    { id: 31, parameterId: 14, relatedExpressionId: 0,  title: 'Средства бюджета'},
    { id: 32, parameterId: 14, relatedExpressionId: 0,  title: 'Внебюджетные средства'},
    { id: 33, parameterId: 15, relatedExpressionId: 0,  title: 'Требуется'},
    { id: 34, parameterId: 15, relatedExpressionId: 0,  title: 'Не требуется'},
]);
